# Generated by Django 3.2.7 on 2023-02-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoradditionalkycdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails'),
        ),
        migrations.AddField(
            model_name='investoraddressdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails'),
        ),
        migrations.AddField(
            model_name='investorbankdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails'),
        ),
        migrations.AddField(
            model_name='investoridentitydetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails'),
        ),
        migrations.AddField(
            model_name='investornomineedetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails'),
        ),
        migrations.AddField(
            model_name='requestdetails',
            name='depository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depository', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestdetails',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investoradditionalkycdetails',
            name='declaration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_declaration_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_declaration_2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
