# Generated by Django 3.2.7 on 2023-02-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0002_auto_20230210_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetails',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
