# Generated by Django 3.2.7 on 2023-02-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depository', '0003_requestdetails_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depository_number', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('depository_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investoraddressdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investorbankdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='requestdetails',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestdetails',
            name='requestno',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='ChooseInvestorIdentityDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('depository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.depository')),
                ('fields', models.ManyToManyField(related_name='field_choices', to='depository.InvestorIdentityDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='requestdetails',
            name='depository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.depository'),
        ),
    ]
