# Generated by Django 3.2.7 on 2023-02-11 09:27

import depository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0004_auto_20230211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depository',
            name='depository_number',
            field=models.CharField(blank=True, default=depository.models.Depository.create_new_depository_unique_no, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='requestdetails',
            name='requestno',
            field=models.CharField(blank=True, default=depository.models.RequestDetails.create_new_request_unique_no, max_length=12, null=True),
        ),
    ]
