# Generated by Django 3.2.7 on 2023-02-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0005_auto_20230211_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChooseInvestorIdentityDetailsField',
        ),
    ]
