# Generated by Django 3.2.7 on 2023-02-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0006_delete_chooseinvestoridentitydetailsfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='depository',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='depository_logo/'),
        ),
        migrations.AddField(
            model_name='requestdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InvestorGaurdianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaurdian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('pancard', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.CharField(blank=True, max_length=60, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_status', models.CharField(blank=True, max_length=50, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
    ]
