# Generated by Django 3.2.7 on 2023-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0007_auto_20230217_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='depository',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depository',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
