# Generated by Django 3.2.7 on 2023-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0009_auto_20230217_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoridentitydetails',
            name='resident_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
