# Generated by Django 3.2.7 on 2023-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0010_investoridentitydetails_resident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoradditionalkycdetails',
            name='kycdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
