# Generated by Django 3.2.7 on 2023-02-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0011_investoradditionalkycdetails_kycdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraddressdetails',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
