# Generated by Django 3.2.7 on 2023-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0012_investoraddressdetails_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='investornomineedetails',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
