# Generated by Django 3.2.7 on 2023-02-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0013_investornomineedetails_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='investornomineedetails',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
