# Generated by Django 3.2.7 on 2023-02-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0014_investornomineedetails_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investornomineedetails',
            old_name='prefix',
            new_name='title',
        ),
    ]
