# Generated by Django 3.2.7 on 2023-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0015_rename_prefix_investornomineedetails_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='investornomineedetails',
            name='nominee_pancard',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
