# Generated by Django 3.2.7 on 2023-02-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0016_investornomineedetails_nominee_pancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoridentitydetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestorStandingInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_1', models.BooleanField(blank=True, default=False, null=True)),
                ('declaration_2', models.BooleanField(blank=True, default=False, null=True)),
                ('account_statement', models.CharField(blank=True, max_length=50, null=True)),
                ('declaration_3', models.BooleanField(blank=True, default=False, null=True)),
                ('declaration_4', models.BooleanField(blank=True, default=False, null=True)),
                ('annual_report', models.CharField(blank=True, max_length=50, null=True)),
                ('declaration_5', models.BooleanField(blank=True, default=False, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorSmsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.BooleanField(blank=True, default=False, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorOtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_annual_income_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('declaration', models.CharField(blank=True, max_length=50, null=True)),
                ('other_info', models.CharField(blank=True, max_length=100, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.requestdetails')),
            ],
        ),
    ]
