# Generated by Django 3.2.7 on 2023-02-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0017_auto_20230226_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorotherdetails',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
