# Generated by Django 3.2.7 on 2023-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0018_investorotherdetails_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='declaration_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='declaration_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='declaration_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='declaration_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='declaration_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
