# Generated by Django 3.2.7 on 2023-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0020_auto_20230317_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investornomineedetails',
            old_name='nominee_email_id',
            new_name='nominee_email',
        ),
        migrations.RemoveField(
            model_name='investornomineedetails',
            name='nominee_pancard',
        ),
        migrations.AddField(
            model_name='investornomineedetails',
            name='nominee_aadhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investornomineedetails',
            name='nominee_nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
