# Generated by Django 3.2.7 on 2023-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0021_auto_20230503_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
