# Generated by Django 3.2.7 on 2023-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0023_alter_investoraddressdetails_residence_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoridentitydetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_details', to='depository.requestdetails'),
        ),
    ]
