# Generated by Django 3.2.7 on 2023-05-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0024_alter_investoridentitydetails_request_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoraccounttype',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investoradditionalkycdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investoraddressdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investorbankdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investordeclaration',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investorgaurdiandetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaurdian_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominee_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investorotherdetails',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investorsmsalert',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_details', to='depository.requestdetails'),
        ),
        migrations.AlterField(
            model_name='investorstandinginstructions',
            name='request_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_details', to='depository.requestdetails'),
        ),
    ]
