# Generated by Django 3.2.7 on 2023-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0025_auto_20230517_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investornomineedetails',
            old_name='nominee_name',
            new_name='nominee_firstname',
        ),
        migrations.AddField(
            model_name='investornomineedetails',
            name='nominee_lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investornomineedetails',
            name='nominee_middlename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetails',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
    ]
