# Generated by Django 3.2.7 on 2023-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0028_investordocumentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraddressdetails',
            name='addr_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
