# Generated by Django 3.2.7 on 2023-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0029_investoraddressdetails_addr_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoraddressdetails',
            name='addr_checkbox',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
