# Generated by Django 3.2.7 on 2023-02-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoryApplicationFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investory_detail_fields', models.CharField(blank=True, choices=[('id', 'id'), ('request_no', 'request_no'), ('applicant_name', 'applicant_name'), ('maiden_name', 'maiden_name'), ('father_spouse_name', 'father_spouse_name'), ('mother_name', 'mother_name'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('martial_status', 'martial_status'), ('nationality', 'nationality'), ('pan_no', 'pan_no'), ('aadhar_no', 'aadhar_no')], max_length=200, null=True)),
                ('depository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
