# Generated by Django 3.2.7 on 2023-02-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depositoryapplicationfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositoryApplicationFields',
        ),
    ]
