# Generated by Django 3.2.7 on 2023-02-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0006_delete_chooseinvestoridentitydetailsfield'),
        ('core', '0003_delete_depositoryapplicationfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseInvestorIdentityDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(blank=True, max_length=30, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('depository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.depository')),
            ],
        ),
    ]
