# Generated by Django 3.2.7 on 2023-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chooseinvestoridentitydetailsfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooseinvestoridentitydetailsfield',
            name='fields',
            field=models.CharField(blank=True, choices=[('applicant_name', 'applicant_name'), ('maiden_name', 'maiden_name'), ('father_spouse_name', 'father_spouse_name'), ('mother_name', 'mother_name'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('martial_status', 'martial_status'), ('nationality', 'nationality'), ('pan_no', 'pan_no'), ('aadhar_no', 'aadhar_no')], max_length=30, null=True),
        ),
    ]
