# Generated by Django 3.2.7 on 2023-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chooseinvestoridentitydetailsfield_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorIdentityDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='chooseinvestoridentitydetailsfield',
            name='fields',
        ),
        migrations.AddField(
            model_name='chooseinvestoridentitydetailsfield',
            name='fields',
            field=models.ManyToManyField(to='core.InvestorIdentityDetailsField'),
        ),
    ]
