# Generated by Django 3.2.7 on 2023-02-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depository', '0006_delete_chooseinvestoridentitydetailsfield'),
        ('core', '0006_auto_20230211_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseInvestorFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('depository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depository.depository')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAdditionalKycDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAddressDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorBankDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorNomineeDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='investoridentitydetailsfield',
            old_name='name',
            new_name='field',
        ),
        migrations.DeleteModel(
            name='ChooseInvestorIdentityDetailsField',
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorAdditionalKycDetailsFields',
            field=models.ManyToManyField(to='core.InvestorAdditionalKycDetailsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorAddressDetailsFields',
            field=models.ManyToManyField(to='core.InvestorAddressDetailsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorBankDetailsFields',
            field=models.ManyToManyField(to='core.InvestorBankDetailsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorIdentityDetailsFields',
            field=models.ManyToManyField(to='core.InvestorIdentityDetailsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorNomineeDetailsFields',
            field=models.ManyToManyField(to='core.InvestorNomineeDetailsField'),
        ),
    ]
