# Generated by Django 3.2.7 on 2023-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_errorsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccountTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorGaurdianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorAccountTypeFields',
            field=models.ManyToManyField(to='core.InvestorAccountTypeField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorGaurdianDetailsFields',
            field=models.ManyToManyField(to='core.InvestorGaurdianDetails'),
        ),
    ]
