# Generated by Django 3.2.7 on 2023-02-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230217_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorOtherDetailsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorSmsAlertField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorStandingInstructionsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
    ]
