# Generated by Django 3.2.7 on 2023-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_investorotherdetailsfield_investorsmsalertfield_investorstandinginstructionsfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDeclarationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorOtherDetailsFields',
            field=models.ManyToManyField(to='core.InvestorOtherDetailsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorSmsAlertFields',
            field=models.ManyToManyField(to='core.InvestorSmsAlertField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorStandingInstructionsFields',
            field=models.ManyToManyField(to='core.InvestorStandingInstructionsField'),
        ),
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorDeclarationFields',
            field=models.ManyToManyField(to='core.InvestorDeclarationField'),
        ),
    ]
