# Generated by Django 3.2.7 on 2023-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usertype_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSelectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocumentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=60)),
                ('documents', models.ManyToManyField(to='core.InvestorSelectDocument')),
            ],
        ),
    ]
