# Generated by Django 3.2.7 on 2023-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_investordocumentmanager_investorselectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorDocumentManagerFields',
            field=models.ManyToManyField(to='core.InvestorDocumentManager'),
        ),
    ]
