# Generated by Django 3.2.7 on 2023-06-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230608_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooseinvestorfields',
            name='investorMartialManagerFields',
        ),
        migrations.DeleteModel(
            name='InvestorMartialManager',
        ),
        migrations.DeleteModel(
            name='InvestorMartialStatus',
        ),
    ]
