# Generated by Django 3.2.7 on 2023-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230628_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorMaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maritalstatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorMaritalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital', models.ManyToManyField(to='core.InvestorMaritalStatus')),
            ],
        ),
    ]
