# Generated by Django 3.2.7 on 2023-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_investormaritalmanager_investormaritalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='investormaritalmanager',
            name='documentss',
            field=models.ManyToManyField(to='core.InvestorSelectDocument'),
        ),
        migrations.RemoveField(
            model_name='investormaritalmanager',
            name='marital',
        ),
        migrations.AddField(
            model_name='investormaritalmanager',
            name='marital',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='InvestorMaritalStatus',
        ),
    ]
