# Generated by Django 3.2.7 on 2023-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230704_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseinvestorfields',
            name='investorMaritalManagerFields',
            field=models.ManyToManyField(to='core.InvestorMaritalManager'),
        ),
    ]
