# Generated by Django 3.2.7 on 2023-02-05 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_slip', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorIdentityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('martial_status', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('DIVORCED', 'DIVORCED'), ('SEPARATED', 'SEPARATED'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=64, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_martial_status', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('DIVORCED', 'DIVORCED'), ('SEPARATED', 'SEPARATED'), ('OTHER', 'Other')], max_length=64, null=True)),
                ('user_nationality', models.CharField(blank=True, max_length=64, null=True)),
                ('user_employeement', models.CharField(blank=True, choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('STUDENT', 'STUDENT'), ('UNEMPLOYEED', 'UNEMPLOYEED')], max_length=64, null=True)),
                ('user_company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user_income', models.FloatField(blank=True, null=True)),
                ('user_primary_contact', models.CharField(blank=True, max_length=64, null=True)),
                ('user_secondary_contact', models.CharField(blank=True, max_length=64, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email_id', models.CharField(blank=True, max_length=60, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=300, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=60, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=60, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_proof', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_proof', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_proof', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
