# Generated by Django 3.2.7 on 2023-02-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorbankdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investoridentitydetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvestorAddressDetails',
        ),
        migrations.DeleteModel(
            name='InvestorBankDetails',
        ),
        migrations.DeleteModel(
            name='InvestorIdentityDetails',
        ),
    ]
