# Generated by Django 3.2.7 on 2023-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_auto_20230209_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investordetail',
            name='user_company_name',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_dob',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_employeement',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_income',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_martial_status',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_nationality',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_primary_contact',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='user_secondary_contact',
        ),
        migrations.AddField(
            model_name='investordetail',
            name='alternate_email_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='email_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='employeement',
            field=models.CharField(blank=True, choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('STUDENT', 'STUDENT'), ('UNEMPLOYEED', 'UNEMPLOYEED')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='martial_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('DIVORCED', 'DIVORCED'), ('SEPARATED', 'SEPARATED'), ('OTHER', 'Other')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='nationality',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='residence_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='secondary_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='spouse_middle_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='tel_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
