# Generated by Django 3.2.7 on 2023-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_auto_20230316_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressproof',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankproof',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityproof',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sign',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
    ]
