# Generated by Django 3.2.7 on 2023-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20230320_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='investordetail',
            name='proof_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='proof_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='proof_country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='proof_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='proof_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='proof_state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
