# Generated by Django 3.2.7 on 2023-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_auto_20230322_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_address',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_city',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_country',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_district',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_pincode',
        ),
        migrations.RemoveField(
            model_name='investordetail',
            name='proof_state',
        ),
    ]
