# Generated by Django 3.2.7 on 2023-03-23 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0006_auto_20230322_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cc_bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('nominee_date_of_birth', models.DateField(blank=True, null=True)),
                ('nominee_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_address', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_note', models.CharField(blank=True, max_length=150, null=True)),
                ('set_as_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='PanCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pancard', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='OverSeaTaxidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overseatax', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='NomineeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='investor.documentupload')),
            ],
        ),
        migrations.CreateModel(
            name='AadharCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhar', to='investor.documentupload')),
            ],
        ),
    ]
