# Generated by Django 3.2.7 on 2023-03-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_aadharcarddata_bankdata_creditcarddata_documentupload_nomineedata_overseataxiddata_pancarddata_passp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investordetail',
            name='nationality',
            field=models.CharField(blank=True, choices=[('INDIAN', 'INDIAN'), ('NRI', 'NRI'), ('FOREIGNER', 'FOREIGNER')], max_length=64, null=True),
        ),
    ]
