# Generated by Django 3.2.7 on 2023-03-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_alter_investordetail_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NomineeData',
        ),
    ]
