# Generated by Django 3.2.7 on 2023-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_alter_documentupload_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='aadhar_no',
            field=models.CharField(blank=True, choices=[('TELEPHONE_BILL', 'TELEPHONE_BILL'), ('ELECTRIC_BILL', 'ELECTRIC_BILL'), ('UTILITY_BILL', 'UTILITY_BILL'), ('OTHER', 'OTHER')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='oversea_tax',
            field=models.CharField(blank=True, choices=[('TELEPHONE_BILL', 'TELEPHONE_BILL'), ('ELECTRIC_BILL', 'ELECTRIC_BILL'), ('UTILITY_BILL', 'UTILITY_BILL'), ('OTHER', 'OTHER')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pancard_no',
            field=models.CharField(blank=True, choices=[('TELEPHONE_BILL', 'TELEPHONE_BILL'), ('ELECTRIC_BILL', 'ELECTRIC_BILL'), ('UTILITY_BILL', 'UTILITY_BILL'), ('OTHER', 'OTHER')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='passport_data',
            field=models.CharField(blank=True, choices=[('TELEPHONE_BILL', 'TELEPHONE_BILL'), ('ELECTRIC_BILL', 'ELECTRIC_BILL'), ('UTILITY_BILL', 'UTILITY_BILL'), ('OTHER', 'OTHER')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='visa_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
