# Generated by Django 3.2.7 on 2023-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0012_auto_20230328_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='entry_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='entry_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
