# Generated by Django 3.2.7 on 2023-03-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0015_alter_investordetail_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('key', models.BinaryField(blank=True, null=True)),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('document', models.CharField(blank=True, choices=[('AADHAR CARD', 'AADHAR CARD'), ('PAN CARD', 'PAN CARD'), ('PASSPORT', 'PASSPORT'), ('VISA', 'VISA'), ('OVERSEA TAX', 'OVERSEA TAX'), ('UTILITY BILL', 'UTILITY BILL'), ('BANK PASSBOOK', 'BANK PASSBOOK'), ('BANK STATEMENT', 'BANK STATEMENT'), ('BANK CHEQUE', 'BANK STATEMENT'), ('CREDIT CARD', 'BANK STATEMENT')], max_length=64, null=True)),
                ('set_as_primary', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investor.documentupload')),
            ],
        ),
    ]
