# Generated by Django 3.2.7 on 2023-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0016_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressproof',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bankdata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='bankproof',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creditcarddata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='identityproof',
            name='user',
        ),
        migrations.RemoveField(
            model_name='overseataxiddata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='pancarddata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='passportdata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='utilitybilldata',
            name='document_data',
        ),
        migrations.RemoveField(
            model_name='visadata',
            name='document_data',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='cancel_cheque_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='passbook_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='statement_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(blank=True, choices=[('AADHAR CARD', 'AADHAR CARD'), ('PAN CARD', 'PAN CARD'), ('PASSPORT', 'PASSPORT'), ('VISA', 'VISA'), ('OVERSEA TAX', 'OVERSEA TAX'), ('UTILITY BILL', 'UTILITY BILL'), ('BANK PASSBOOK', 'BANK PASSBOOK'), ('BANK STATEMENT', 'BANK STATEMENT'), ('BANK CHEQUE', 'BANK CHEQUE'), ('CREDIT CARD', 'CREDIT CARD')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='oversea_tax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='pancard_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='passport_data',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='AadharCardData',
        ),
        migrations.DeleteModel(
            name='AddressProof',
        ),
        migrations.DeleteModel(
            name='BankData',
        ),
        migrations.DeleteModel(
            name='BankProof',
        ),
        migrations.DeleteModel(
            name='CreditCardData',
        ),
        migrations.DeleteModel(
            name='IdentityProof',
        ),
        migrations.DeleteModel(
            name='OverSeaTaxidData',
        ),
        migrations.DeleteModel(
            name='PanCardData',
        ),
        migrations.DeleteModel(
            name='PassportData',
        ),
        migrations.DeleteModel(
            name='SalarySlip',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.DeleteModel(
            name='UtilityBillData',
        ),
        migrations.DeleteModel(
            name='VisaData',
        ),
    ]
