# Generated by Django 3.2.7 on 2023-03-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0019_auto_20230330_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investordetail',
            old_name='father_f_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='father_l_name',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='father_m_name',
            new_name='father_middle_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='mother_f_name',
            new_name='mother_first_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='mother_l_name',
            new_name='mother_last_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='mother_m_name',
            new_name='mother_middle_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='spouse_f_name',
            new_name='spouse_first_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='spouse_l_name',
            new_name='spouse_last_name',
        ),
        migrations.RenameField(
            model_name='investordetail',
            old_name='spouse_m_name',
            new_name='spouse_middle_name',
        ),
    ]
