# Generated by Django 3.2.7 on 2023-04-03 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0020_auto_20230330_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
