# Generated by Django 3.2.7 on 2023-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0021_auto_20230403_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investordetail',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
