# Generated by Django 3.2.7 on 2023-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0023_alter_documentupload_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='nominee_aadhar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='nominee_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
