# Generated by Django 3.2.7 on 2023-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0024_auto_20230404_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investordetail',
            name='residence_address',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='broker_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='bldg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='flat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investordetail',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
