# Generated by Django 3.2.7 on 2023-04-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0026_auto_20230405_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfileMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING APPROVAL', 'PENDING APPROVAL'), ('ACCEPETD', 'ACCEPETD'), ('REJCTED', 'REJCTED')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
