# Generated by Django 3.2.7 on 2023-04-06 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0027_investorprofilemerge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='relation',
            field=models.CharField(blank=True, choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING APPROVAL', 'PENDING APPROVAL'), ('ACCEPETD', 'ACCEPETD'), ('REJECTED', 'REJECTED')], max_length=20, null=True),
        ),
    ]
