# Generated by Django 3.2.7 on 2023-04-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0028_auto_20230406_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='set_as_primary',
        ),
        migrations.CreateModel(
            name='InvestorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_from', models.DateField(blank=True, null=True)),
                ('entry_to', models.DateField(blank=True, null=True)),
                ('passbook_number', models.CharField(blank=True, max_length=20, null=True)),
                ('statement_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cancel_cheque_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('set_as_primary', models.BooleanField(default=False)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='investor.investordetail')),
            ],
        ),
    ]
