# Generated by Django 3.2.7 on 2023-04-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0029_auto_20230406_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='branch_address',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='cancel_cheque_no',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='city',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='country',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='entry_from',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='entry_to',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='ifsc_number',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='micr_number',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='passbook_number',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='state',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='statement_no',
        ),
    ]
