# Generated by Django 3.2.7 on 2023-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0030_auto_20230406_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='bill',
            new_name='bill_name',
        ),
        migrations.RemoveField(
            model_name='investorbankdetail',
            name='cancel_cheque_no',
        ),
        migrations.RemoveField(
            model_name='investorbankdetail',
            name='passbook_number',
        ),
        migrations.RemoveField(
            model_name='investorbankdetail',
            name='statement_no',
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='employeement',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Private Sector Service', 'Private Sector Service'), ('Public Sector', 'Public Sector'), ('Retired', 'Retired'), ('Govt Service', 'Govt Service'), ('Professional', 'Professional'), ('Agricultural', 'Agricultural'), ('Housewife', 'Housewife'), ('Forex Dealer', 'Forex Dealer'), ('Others', 'Others')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='martial_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('DIVORCED', 'DIVORCED'), ('SEPARATED', 'SEPARATED'), ('OTHER', 'OTHER')], max_length=64, null=True),
        ),
    ]
