# Generated by Django 3.2.7 on 2023-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0031_auto_20230407_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorbankdetail',
            old_name='entry_from',
            new_name='pb_entry_from',
        ),
        migrations.RenameField(
            model_name='investorbankdetail',
            old_name='entry_to',
            new_name='pb_entry_to',
        ),
        migrations.AddField(
            model_name='investorbankdetail',
            name='st_entry_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorbankdetail',
            name='st_entry_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
