# Generated by Django 3.2.7 on 2023-04-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0033_alter_documentupload_nominee_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='cc_bank_name',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='cc_limit',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='cc_number',
        ),
        migrations.CreateModel(
            name='InvestorCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('set_as_primary', models.BooleanField(default=False)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_details', to='investor.investordetail')),
            ],
        ),
    ]
