# Generated by Django 3.2.7 on 2023-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0034_auto_20230410_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='cc_bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='cc_limit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='cc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='InvestorCreditCard',
        ),
    ]
