# Generated by Django 3.2.7 on 2023-04-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0037_alter_investorcreditcard_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcreditcard',
            name='document_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_details', to='investor.investordetail'),
        ),
    ]
