# Generated by Django 3.2.7 on 2023-04-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0039_auto_20230413_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofilemerge',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRO', 'NRO'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Amex', 'Amex'), ('Other', 'Other'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_merge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_merge', to=settings.AUTH_USER_MODEL),
        ),
    ]
