# Generated by Django 3.2.7 on 2023-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0041_auto_20230420_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='aadhar_no',
            new_name='aadhar_father_no',
        ),
        migrations.RenameField(
            model_name='documentupload',
            old_name='pancard_no',
            new_name='aadhar_mother_no',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='aadhar_self_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='aadhar_spouse_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pancard_father_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pancard_mother_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pancard_self_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='pancard_spouse_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('Other', 'Other'), ('Master Card', 'Master Card'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
