# Generated by Django 3.2.7 on 2023-05-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0042_auto_20230420_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('NRO', 'NRO'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('Master Card', 'Master Card'), ('VISA', 'VISA'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
