# Generated by Django 3.2.7 on 2023-05-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0043_auto_20230502_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_aadhar',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_address',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_email',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_name',
        ),
        migrations.RemoveField(
            model_name='documentupload',
            name='nominee_relationship',
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('VISA', 'VISA'), ('Amex', 'Amex'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='InvestorNomineeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('nominee_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('nominee_date_of_birth', models.DateField(blank=True, null=True)),
                ('nominee_relationship', models.CharField(blank=True, choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('nominee_address', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_email', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_aadhar', models.CharField(blank=True, max_length=300, null=True)),
                ('document_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_details', to='investor.investordetail')),
            ],
        ),
    ]
