# Generated by Django 3.2.7 on 2023-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0044_auto_20230502_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='investornomineedetail',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('NRE', 'NRE'), ('CURRENT', 'CURRENT'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Amex', 'Amex'), ('VISA', 'VISA'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
