# Generated by Django 3.2.7 on 2023-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0045_auto_20230502_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
