# Generated by Django 3.2.7 on 2023-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0047_auto_20230504_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofilemerge',
            name='permission',
            field=models.CharField(blank=True, choices=[('Read/Write', 'Read/Write'), ('Read', 'Read')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('VISA', 'VISA'), ('Other', 'Other'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
    ]
