# Generated by Django 3.2.7 on 2023-05-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0048_auto_20230506_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Other', 'Other'), ('Master Card', 'Master Card'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetail',
            name='nominee_relationship',
            field=models.CharField(blank=True, choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('WIFE', 'WIFE'), ('HUSBAND', 'HUSBAND'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='relation',
            field=models.CharField(blank=True, choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('WIFE', 'WIFE'), ('HUSBAND', 'HUSBAND'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
    ]
