# Generated by Django 3.2.7 on 2023-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0049_auto_20230510_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Amex', 'Amex'), ('Other', 'Other'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
