# Generated by Django 3.2.7 on 2023-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0050_auto_20230510_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='investordetail',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
