# Generated by Django 3.2.7 on 2023-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0051_auto_20230510_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Amex', 'Amex'), ('VISA', 'VISA'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('OTHER', 'OTHER')], max_length=64, null=True),
        ),
    ]
