# Generated by Django 3.2.7 on 2023-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0052_auto_20230510_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofilemerge',
            name='set_as_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
