# Generated by Django 3.2.7 on 2023-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0053_auto_20230511_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofilemerge',
            name='set_as_primary',
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Amex', 'Amex'), ('Master Card', 'Master Card'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofilemerge',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING APPROVAL', 'PENDING APPROVAL'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=20, null=True),
        ),
    ]
