# Generated by Django 3.2.7 on 2023-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0055_auto_20230517_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investornomineedetail',
            old_name='nominee_name',
            new_name='nominee_firstname',
        ),
        migrations.AddField(
            model_name='investornomineedetail',
            name='nominee_lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investornomineedetail',
            name='nominee_middlename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Amex', 'Amex'), ('VISA', 'VISA'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investornomineedetail',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
    ]
