# Generated by Django 3.2.7 on 2023-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0056_auto_20230517_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Amex', 'Amex'), ('Master Card', 'Master Card'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
