# Generated by Django 3.2.7 on 2023-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0057_alter_investorcreditcard_cc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('NRO', 'NRO'), ('NRE', 'NRE'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
