# Generated by Django 3.2.7 on 2023-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0058_auto_20230518_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('NRE', 'NRE'), ('SAVING', 'SAVING'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Other', 'Other'), ('Master Card', 'Master Card'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
