# Generated by Django 3.2.7 on 2023-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0059_auto_20230518_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('NRE', 'NRE'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='ifsc_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
