# Generated by Django 3.2.7 on 2023-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0060_auto_20230530_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
