# Generated by Django 3.2.7 on 2023-05-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0061_auto_20230530_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('VISA', 'VISA'), ('Other', 'Other'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
    ]
