# Generated by Django 3.2.7 on 2023-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0062_auto_20230530_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('SAVING', 'SAVING'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('VISA', 'VISA'), ('Amex', 'Amex'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
    ]
