# Generated by Django 3.2.7 on 2023-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0063_auto_20230606_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('SAVING', 'SAVING'), ('NRO', 'NRO'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Amex', 'Amex'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
