# Generated by Django 3.2.7 on 2023-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0064_auto_20230606_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('NRE', 'NRE'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('VISA', 'VISA'), ('Amex', 'Amex'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
