# Generated by Django 3.2.7 on 2023-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0065_auto_20230607_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
