# Generated by Django 3.2.7 on 2023-06-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0066_auto_20230607_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(blank=True, choices=[('AADHAR CARD SELF', 'AADHAR CARD SELF'), ('AADHAR CARD FATHER', 'AADHAR CARD FATHER'), ('AADHAR CARD MOTHER', 'AADHAR CARD MOTHER'), ('AADHAR CARD SPOUSE', 'AADHAR CARD SELF'), ('PAN CARD SELF', 'PAN CARD SELF'), ('PAN CARD FATHER', 'PAN CARD FATHER'), ('PAN CARD MOTHER', 'PAN CARD MOTHER'), ('PAN CARD SPOUSE', 'PAN CARD SPOUSE'), ('PASSPORT', 'PASSPORT'), ('VISA', 'VISA'), ('OVERSEA TAX', 'OVERSEA TAX'), ('UTILITY BILL', 'UTILITY BILL'), ('BANK PASSBOOK', 'BANK PASSBOOK'), ('BANK STATEMENT', 'BANK STATEMENT'), ('BANK CHEQUE', 'BANK CHEQUE'), ('CREDIT CARD', 'CREDIT CARD')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('NRE', 'NRE'), ('NRO', 'NRO'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Amex', 'Amex'), ('Other', 'Other'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
    ]
