# Generated by Django 3.2.7 on 2023-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0067_auto_20230608_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('NRO', 'NRO'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Amex', 'Amex'), ('Master Card', 'Master Card'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
