# Generated by Django 3.2.7 on 2023-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0068_auto_20230628_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('VISA', 'VISA'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
