# Generated by Django 3.2.7 on 2023-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0069_auto_20230628_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('Other', 'Other'), ('Master Card', 'Master Card'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
