# Generated by Django 3.2.7 on 2023-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0070_auto_20230704_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('SAVING', 'SAVING'), ('NRO', 'NRO'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Master Card', 'Master Card'), ('VISA', 'VISA'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
