# Generated by Django 3.2.7 on 2023-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0071_auto_20230704_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRE', 'NRE'), ('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Amex', 'Amex'), ('Other', 'Other'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
