# Generated by Django 3.2.7 on 2023-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0072_auto_20230704_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('SAVING', 'SAVING'), ('NRE', 'NRE'), ('CURRENT', 'CURRENT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('VISA', 'VISA'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
