# Generated by Django 3.2.7 on 2023-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0073_auto_20230704_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
