# Generated by Django 3.2.7 on 2023-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0074_alter_investorcreditcard_cc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'CURRENT'), ('SAVING', 'SAVING'), ('NRE', 'NRE'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Other', 'Other'), ('Amex', 'Amex'), ('Master Card', 'Master Card')], max_length=20, null=True),
        ),
    ]
