# Generated by Django 3.2.7 on 2023-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0075_auto_20230704_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Master Card', 'Master Card'), ('VISA', 'VISA'), ('Other', 'Other'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
