# Generated by Django 3.2.7 on 2023-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0077_alter_investorcreditcard_cc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('NRO', 'NRO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('Amex', 'Amex'), ('Other', 'Other'), ('Master Card', 'Master Card'), ('VISA', 'VISA')], max_length=20, null=True),
        ),
    ]
