# Generated by Django 3.2.7 on 2023-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0078_auto_20230707_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetail',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NRO', 'NRO'), ('CURRENT', 'CURRENT'), ('NRE', 'NRE'), ('SAVING', 'SAVING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investorcreditcard',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('Master Card', 'Master Card'), ('Other', 'Other'), ('Amex', 'Amex')], max_length=20, null=True),
        ),
    ]
